### ISSUE TITLE
how to connect to local dynamo DB in docker compose?

### ISSUE THREAD

**Issue by davidxiao** [chiefbiiko/dynamodb#23]
Hi,
   it can connect to separate dynamoDB, while when all the service and DynamoDB in one docker compose, then `local` seems not work,
  maybe need to update some logic update fixed `localhost`  when region is `local`?

**Comment by davidxiao** [comment]
can not connect to dynamoDB from docker-compose:
```
{
  credentials: {
    accessKeyId: "DynamoDBLocal",
    secretAccessKey: "DoesNotDoAnyAuth",
    sessionToken: "preferTemporaryCredentials"
  },
  region: "local",
  host: "dynamodb",
  port: 8001,
  cache: {
    _credentialScope: "",
    _signingKey: null,
    _accessKeyId: "",
    _sessionToken: "",
    refresh: [AsyncFunction: refresh],
    signingKey: null,
    credentialScope: "",
    accessKeyId: "",
    sessionToken: ""
  },
  method: "POST",
  endpoint: "http://dynamodb:8001/"
}
```

got error:
```
error: Uncaught Http: error sending request for url (http://dynamodb:8001/): error trying to connect: tcp connect error: Connection refused (os error 111)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async fetch ($deno$/web/fetch.ts:591:27)
```
it works without docker-compose,
the only difference I made is, in docker-compose, i use `dynamodb`, and use `localhost` without docker-compose,
