### ISSUE TITLE
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'

### ISSUE THREAD

**Issue by helloworldless** [chiefbiiko/dynamodb#28]
It looks like since Deno 1.5, there was a [breaking change](https://deno.com/blog/v1.5#stricter-type-checks-in-stable) which is causing an issue. I'm running Deno 1.17.2 and seeing this error:

```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Doc } from "./util.ts";
         ~~~
    at https://denopkg.com/chiefbiiko/dynamodb@v1.0.0/mod.ts:5:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { HeadersConfig, createHeaders } from "./create_headers.ts";
         ~~~~~~~~~~~~~
    at https://denopkg.com/chiefbiiko/dynamodb@v1.0.0/client/mod.ts:4:10

Found 2 errors.
```

I found some solutions saying to create a tsconfig.json like this:

```
{
  "compilerOptions": {
    "isolatedModules": false,
  }
}
```

... but it did not solve the issue.

A bit more research turned up this saying that isolatedModules cannot be disabled: https://github.com/denoland/deno/issues/12599

**Comment by Alxblsk** [comment]
@chiefbiiko I've created a tiny PR to address this issue. Would be great if you can take a look.

**Comment by webbrain-one** [comment]
Thanks for reporting! I opened [PR #33](https://github.com/chiefbiiko/dynamodb/pull/33) to fix this by updating the affected re-exports to use `export type`, which satisfies Deno’s stricter `--isolatedModules` checks.
